apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: extract-values-file
spec:
  params:
    - name: TAR_URL
      type: string
    - name: VALUES_PATH
      type: string
  workspaces:
    - name: shared-data
  results:
    - name: values_file

  steps:
    - image: ubuntu # docker.io/guybalmas/ubuntu-utils:1.0.0@sha256:8a47b0857f3ba3fb1f65d42c918ed7a937bb1e1857b60f2f79d22ca0299a2fa9 # contains curl
      name: get-source-tar
      workingDir: $(workspaces.shared-data.path)
      script: |
        #!/usr/bin/env bash
        echo "$(date)" > $(workspaces.shared-data.path)/start.time
        sudo apt update && sudo apt upgrade && sudo apt install curl
        rm -rf source-code
        mkdir source-code && cd source-code
        echo ">>> Cloning and unpacking tar.gz file:"
        echo ">>> Downloading artifact: $(params.TAR_URL)"
        curl $(params.TAR_URL) --output app.tar.gz
    - image: ubuntu # contains bash
      name: unpack-tar
      workingDir: $(workspaces.shared-data.path)
      script: |
        #!/usr/bin/env bash
        echo ">>> Unpacking artifact"
        cd $(workspaces.shared-data.path)/source-code
        mkdir example-app
        tar -xvzf app.tar.gz -C example-app/
        cd example-app
        ls
        echo "Source files full path: $PWD"
    
    - image: ubuntu # contains bash
      name: export-values-file
      workingDir: $(workspaces.shared-data.path)
      script: |
        #!/usr/bin/env bash
        echo ">>> Exporting values.yaml"
        cd $(workspaces.shared-data.path)/source-code
        values_content=$(cat $(params.VALUES_PATH))
        echo "values.yaml file: $(values_content)"
        echo -n "Exporting 'values_file' result: "
        echo -n $(values_content) | tee $(results.values_file.path)