apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: extract-values-file-runtemplate
spec:
  outputs:
    values_file: .status.taskResults[?(@.name=="values_file")].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      params: $(runnable.spec.inputs.params)$
      serviceAccountName: $(runnable.spec.inputs.serviceAccount)$
      taskRef:
        kind: ClusterTask
        name: extract-values-file
